FROM pytorch/torchserve:latest

WORKDIR /home/model-server

COPY model-store ./model-store
COPY torchserve/config.properties ./config.properties

EXPOSE 8080 8081 8082

CMD ["torchserve", "--start", "--ncs", "--model-store", "model-store", "--ts-config", "config.properties", "--foreground"]
